add domain model classes: Clinic, Medical Service, Doctor
eugene-mytrofanov/hospital-services pull request #1
Opened 2019-05-17 13:44 UTC by eugene-mytrofanov

2019-05-18 18:07 UTC, Andriireva requested changes

2019-05-18 18:07 UTC, Andriireva commented on src/main/java/ua/su/model/Clinic.java
> +    private boolean isPrivateClinic;
Лучше делать тип обертку - Boolean

2019-05-18 18:07 UTC, Andriireva commented on src/main/java/ua/su/model/Clinic.java
> +    private boolean isInsuranceSupported;
Тоже самое что вверху

2019-05-18 18:07 UTC, Andriireva commented on src/main/java/ua/su/model/Clinic.java
> +    private ArrayList<Doctor> doctors;
Тип лучше всегда делать интерфейсом - List

2019-05-18 18:07 UTC, Andriireva commented on src/main/java/ua/su/model/Clinic.java
> +    private ArrayList<MedicalService> services;
Тоже самое что и вверху. имя лучше переименовать в midicalServices

2019-05-18 18:07 UTC, Andriireva commented on src/main/java/ua/su/model/Clinic.java
> +    public Clinic(String name, String address, String phone, boolean isPrivateClinic, boolean isInsuranceSupported,
Используем обертки и интерфейсы - Boolean и List

2019-05-18 18:07 UTC, Andriireva commented on src/main/java/ua/su/model/MedicalService.java
> +public class MedicalService {
Лучше использовать обертки а не примитивы. int -> Integer, double -> Double

2019-05-18 18:10 UTC, Andriireva requested changes

2019-05-18 18:10 UTC, Andriireva commented on src/main/java/ua/su/model/Clinic.java
> +public class Clinic {
Не хватает поля - "колчество врачей"

2019-05-18 18:10 UTC, Andriireva commented on src/main/java/ua/su/model/Clinic.java
> +    private ArrayList<Doctor> doctors;
В задаче ничего про доктора не говорилось, нет необходимости в списке докторов

2019-05-20 02:22 UTC, eugene-mytrofanov commented on src/main/java/ua/su/model/Clinic.java
> +    private boolean isPrivateClinic;
The type has been changed to Boolean.

2019-05-20 02:23 UTC, eugene-mytrofanov commented on src/main/java/ua/su/model/Clinic.java
> +    private boolean isInsuranceSupported;
Changed to Boolean.

2019-05-20 02:35 UTC, eugene-mytrofanov commented on src/main/java/ua/su/model/Clinic.java
> +    private ArrayList<MedicalService> services;
The variable 'services' has been renamed to medicalServices

2019-05-20 03:22 UTC, eugene-mytrofanov commented on src/main/java/ua/su/model/Clinic.java
> +    public Clinic(String name, String address, String phone, boolean isPrivateClinic, boolean isInsuranceSupported,
Done, thanks.

2019-05-20 03:26 UTC, eugene-mytrofanov commented on src/main/java/ua/su/model/MedicalService.java
> +public class MedicalService {
Integer and Double were applied according to the comment.

2019-05-20 03:34 UTC, eugene-mytrofanov commented on src/main/java/ua/su/model/Clinic.java
> +public class Clinic {
The Integer numberOfDoctors has been added.

2019-05-20 03:35 UTC, eugene-mytrofanov commented on src/main/java/ua/su/model/Clinic.java
> +    private ArrayList<Doctor> doctors;
The field has been modified and Doctor class is removed.

2019-05-21 12:49 UTC, Andriireva requested changes

2019-05-21 12:49 UTC, Andriireva commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://medicalProcedures.gradle.org/distributions/gradle-4.10.3-bin.zip
Это не надо менять должно быть https\://services.gradle.org/distributions/gradle-4.10.3-bin.zip

2019-05-22 03:15 UTC, eugene-mytrofanov commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://medicalProcedures.gradle.org/distributions/gradle-4.10.3-bin.zip
@Andriireva Не убрал из автоматического рефакторинга. Вернул обратно на https://services.gradle.org/distributions/gradle-4.10.3-bin.zip, закоммитил и запушил.

2019-05-22 06:59 UTC, Andriireva approved these changes

2019-05-22 13:53 UTC, merged